# Generated by Django 3.2.6 on 2021-09-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuseranswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
