# Generated by Django 3.2.6 on 2021-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizuseranswer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizuseranswer',
            name='score',
        ),
        migrations.AlterField(
            model_name='quizenrolleduser',
            name='is_enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
